[package]
name = "v4l2-nctl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
v4l = "0.13.1"
tui = "0.19.0"
crossterm =  "0.25"
